### ISSUE TITLE
Realtime BBS Linux Lib

### ISSUE THREAD

**Issue by StuartIanNaylor** [JusperLee/Speech-Separation-Paper-Tutorial#11]
I wonder if anyone will ever produce a realtime lib that the output you can put back on a loopback.

There is a real struggle for any highly optimised DSP libs for linux and its not as if commercial alternatives don't exist much even runs on microcontrollers but from searching nothing seems to exist.
What be great if you had another category for embedded (specifically the Pi)

**Comment by YangLiu-QUST** [comment]
邮件已收到メールは届きました

**Comment by YangLiu-QUST** [comment]
邮件已收到メールは届きました

**Comment by StuartIanNaylor** [comment]
Email never arrived as been checking both inbox and junk, oh well ...
